export const modalStyles = {
    addButtonContainer: {
      border: '1px solid #333',
      borderRadius: '5px',
      padding: '20px',
      position: 'relative',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      height: '150px',
      width: '200px', 
    },
    addButton: {
      fontSize: '30px',
      color: '#333',
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
    },
  };