export const modalStyles = {
    overlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    modal: {
      background: 'white',
      padding: '20px',
      borderRadius: '5px',
      width: '400px',
      boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    },
    title: {
      margin : '0 0 10px',
      fontSize: '24px',
      fontWeight: 'bold',
    },
    subtitle: {
      margin: '0 0 15px',
      fontSize: '18px',
      fontWeight: '600',
    },
    vmList: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '10px',
      maxHeight: '200px',
      overflowY: 'auto',
      marginBottom: '20px',
    },
    vmItem: {
      display: 'flex',
      alignItems: 'center',
    },
    vmName: {
      cursor: 'pointer',
      padding: '10px',
      borderRadius: '4px',
      transition: 'background-color 0.3s',
    },
    vmDetails: {
      marginTop: '20px',
      border: '1px solid #ccc',
      padding: '10px',
    },
    input: {
      width: '100%',
      padding: '10px',
      margin: '10px 0',
      border: '1px solid #ccc',
      borderRadius: '4px',
    },
    buttonContainer: {
      display: 'flex',
      justifyContent: 'flex-end',
    },
    okButton: {
      padding: '10px 15px',
      backgroundColor: '#007bff',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
    },
    tooltipContainer: {
      position: 'relative',
      display: 'inline-block',
      marginLeft: '5px',
      verticalAlign: 'middle',
    },
    helpIcon: {
      width: '20px',
      height: '20px',
      cursor: 'pointer',
      verticalAlign: 'middle',
    },
    tooltip: {
      visibility: 'hidden',
      width: '120px',
      backgroundColor: 'black',
      color: '#fff',
      textAlign: 'center',
      borderRadius: '5px',
      padding: '5px',
      position: 'absolute',
      zIndex: 1,
      bottom: '125%',
      left: '50%',
      marginLeft: '-60px',
      opacity: 0,
      transition: 'opacity 0.3s',
    },
    closeButton: {
      position: 'absolute',
      top: '10px',
      left: '10px',
      background: 'none',
      border: 'none',
      fontSize: '20px',
      cursor: 'pointer',
    },
  };