export const modalStyles = {
    overlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    
    },
    modal: {
      background: 'rgb(39, 38, 51)', 
      padding: '5px',
      borderRadius: '20px',
      width: '420px',
      height: 'auto',
      border: '1px solid #7C7A8C' 
  },
    title: {
      marginTop:'15px',
      marginLeft: '15px',
      fontSize: '16px',
      fontWeight: '700',
      color: '#ffffff',
      height:'20px'
    },
    subtitle: {
      color: '#ffffff',
      margin: '0 0 15px',
      fontSize: '16px',
      fontWeight: '600',
      marginTop:'30px',
      marginLeft: '15px',
      height:'20px'
    },
    vmList: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '20px',
      maxHeight: '200px',
      overflowY: 'auto',
      marginBottom: '20px',
      marginTop:'10px',
    },
    vmItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '40px',
    },
    vmName: {
      cursor: 'pointer',
      padding: '10px',
      borderRadius: '4px',
      transition: 'background-color 0.3s',
      fontSize: '14px',
      color: '#ffffff'
    },
    vmDetails: {
      marginTop: '10px',
      border: '1px solid #ccc',
      borderRadius: '10px ',
      padding: '10px',
    },
    input: {
      width: '100%',
      padding: '10px',
      margin: '10px 0',
      border: '1px solid #ccc',
      borderRadius: '4px',
    },
    buttonContainer: {
      display: 'flex',
      justifyContent: 'flex-end',
    },
    okButton: {
      padding: '10px 15px',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      background: 'transparent',
      color:'#ffffff',
      fontSize: '14px',
    },
    tooltipContainer: {
      position: 'relative',
      display: 'inline-block',
      marginLeft: '5px',
      verticalAlign: 'middle',
    },
    helpIcon: {
      width: '20px',
      height: '20px',
      cursor: 'pointer',
      verticalAlign: 'middle',
    },
    tooltip: {
      visibility: 'hidden',
      width: '120px',
      backgroundColor: 'black',
      color: '#fff',
      textAlign: 'center',
      borderRadius: '5px',
      padding: '5px',
      position: 'absolute',
      zIndex: 1,
      bottom: '125%',
      left: '50%',
      marginLeft: '-60px',
      opacity: 0,
      transition: 'opacity 0.3s',
    },
    closeButton: {
      color: '#ffffff',
      position: 'flex',
      top: '10px',
      left: '10px',
      cursor: 'pointer',
      border: 'none',
      background: 'none',
      fontSize: '30px',
      transition: "color 0.3s",
    },
    closeButtonHover: {
        color: 'blue', 
    }
    
  };